import fs from "node:fs";
import path from "node:path";

export async function generateSummary(options = {}) {
  const inFile = options.report || "baseline-report.json";
  const format = options.format || "markdown";
  const outFile = options.out;

  if (!fs.existsSync(inFile)) {
    throw new Error(`Report file "${inFile}" does not exist`);
  }

  let report;
  try {
    report = JSON.parse(fs.readFileSync(inFile, "utf8"));
  } catch (error) {
    throw new Error(`Error reading report file: ${error.message}`);
  }

  const counts = report.results?.reduce((acc, x) => (acc[x.status]=(acc[x.status]||0)+1, acc), {}) || {};
  
  let output;
  
  if (format === "json") {
    output = JSON.stringify({
      summary: {
        scannedFiles: report.metadata?.scannedFiles || 0,
        processedFiles: report.metadata?.processedFiles || 0,
        baselineLike: counts.baseline_like || 0,
        risky: counts.risky || 0,
        unknown: counts.unknown || 0
      },
      results: report.results || []
    }, null, 2);
  } else if (format === "html") {
    output = generateHTMLReport(report, counts);
  } else {
    // Markdown format
    output = `# Baseline Compatibility Report

## Summary
- **Scanned files:** ${report.metadata?.scannedFiles || 0}
- **Processed files:** ${report.metadata?.processedFiles || 0}
- **Results:** 
  - ✅ **Baseline-like:** ${counts.baseline_like || 0}
  - ⚠️ **Risky:** ${counts.risky || 0}
  - ❓ **Unknown:** ${counts.unknown || 0}

## Features

| Feature | Status | Files | MDN |
|---------|--------|-------|-----|
${(report.results || []).slice(0, 50).map(x => 
  `| ${x.feature} | ${x.status} | ${x.files?.slice(0, 3).join("<br>") || ""} | ${x.mdn ? `[Docs](${x.mdn})` : ""} |`
).join("\n")}

${(report.results || []).length > 50 ? `\n_Showing first 50 features. See full \`${inFile}\` for complete details._` : ""}

---
_Generated by baseline-check v${report.metadata?.version || "2.0.0"}_`;
  }

  if (outFile) {
    const outDir = path.dirname(outFile);
    if (!fs.existsSync(outDir)) {
      fs.mkdirSync(outDir, { recursive: true });
    }
    fs.writeFileSync(outFile, output);
    console.log(`✅ Summary report written to: ${outFile}`);
  } else {
    console.log(output);
  }

  return output;
}

function generateHTMLReport(report, counts) {
  return `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Baseline Compatibility Report</title>
    <style>
        body { font-family: system-ui, sans-serif; margin: 0; padding: 20px; background: #f5f5f5; }
        .container { max-width: 1200px; margin: 0 auto; background: white; padding: 20px; border-radius: 8px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
        .summary { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 20px; margin-bottom: 30px; }
        .stat-card { padding: 20px; border-radius: 8px; text-align: center; }
        .baseline-like { background: #e8f5e8; border-left: 4px solid #4caf50; }
        .risky { background: #fff3cd; border-left: 4px solid #ff9800; }
        .unknown { background: #f1f3f5; border-left: 4px solid #6c757d; }
        .stat-number { font-size: 2em; font-weight: bold; margin-bottom: 5px; }
        .stat-label { color: #666; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th, td { padding: 12px; text-align: left; border-bottom: 1px solid #ddd; }
        th { background: #f8f9fa; font-weight: 600; }
        .status { padding: 4px 8px; border-radius: 4px; font-size: 0.9em; }
        .status.baseline_like { background: #d4edda; color: #155724; }
        .status.risky { background: #fff3cd; color: #856404; }
        .status.unknown { background: #f8d7da; color: #721c24; }
        a { color: #007bff; text-decoration: none; }
        a:hover { text-decoration: underline; }
    </style>
</head>
<body>
    <div class="container">
        <h1>Baseline Compatibility Report</h1>
        
        <div class="summary">
            <div class="stat-card">
                <div class="stat-number">${report.metadata?.scannedFiles || 0}</div>
                <div class="stat-label">Files Scanned</div>
            </div>
            <div class="stat-card baseline-like">
                <div class="stat-number">${counts.baseline_like || 0}</div>
                <div class="stat-label">Baseline-like</div>
            </div>
            <div class="stat-card risky">
                <div class="stat-number">${counts.risky || 0}</div>
                <div class="stat-label">Risky</div>
            </div>
            <div class="stat-card unknown">
                <div class="stat-number">${counts.unknown || 0}</div>
                <div class="stat-label">Unknown</div>
            </div>
        </div>

        <h2>Features</h2>
        <table>
            <thead>
                <tr>
                    <th>Feature</th>
                    <th>Status</th>
                    <th>Files</th>
                    <th>Documentation</th>
                </tr>
            </thead>
            <tbody>
                ${(report.results || []).map(x => `
                    <tr>
                        <td><strong>${x.feature}</strong></td>
                        <td><span class="status ${x.status}">${x.status}</span></td>
                        <td>${(x.files || []).slice(0, 3).join("<br>")}</td>
                        <td>${x.mdn ? `<a href="${x.mdn}" target="_blank">MDN Docs</a>` : ""}</td>
                    </tr>
                `).join("")}
            </tbody>
        </table>
        
        <p><em>Generated by baseline-check v${report.metadata?.version || "2.0.0"}</em></p>
    </div>
</body>
</html>`;
}

// CLI interface for backward compatibility
if (import.meta.url === `file://${process.argv[1]}`) {
  const args = new Map();
  const argv = process.argv.slice(2);
  
  for (let i = 0; i < argv.length; i++) {
    if (argv[i].startsWith("--")) {
      const key = argv[i].replace(/^--/, "");
      const value = argv[i + 1] && !argv[i + 1].startsWith("--") ? argv[i + 1] : true;
      args.set(key, value);
      if (typeof value === "string") i++;
    }
  }
  
  const options = {
    report: args.get("report") || "baseline-report.json",
    format: args.get("format") || "markdown",
    out: args.get("out")
  };
  
  try {
    await generateSummary(options);
  } catch (error) {
    console.error(`Summary generation failed: ${error.message}`);
    process.exit(1);
  }
}
